version: '3.4'

services:
  eshop.gateway:
    image: ${DOCKER_REGISTRY-}eshopgateway
    build:
      context: .
      dockerfile: demo/EShop.Gateway/Dockerfile

  eshop.products:
    image: ${DOCKER_REGISTRY-}eshopproducts
    build:
      context: .
      dockerfile: demo/EShop.Products/Dockerfile

